
name: Deploy MkDocs Blog

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List files (for debugging)
        run: ls -R

      - name: Build
        run: |
          ./dev_setup.sh
          pip install mdformat
          pip install mdformat-gfm
          pip install mdformat-gfm mdformat-frontmatter mdformat-footnote
          pip install mdformat-myst
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build
      - uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: build
          branch: gh-pages
      - name: FINAL 
        run: echo "https://torrezmn.github.io/"
