name: Deploy MkDocs Blog   

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files (for debugging)
        run: ls -R

      - name: Setup dependencies
        run: |
          ./dev_setup.sh
          pip install mdformat
          pip install mdformat-gfm
          pip install mdformat-gfm mdformat-frontmatter mdformat-footnote
          pip install mdformat-myst
      - name: Prepare the site
        run: sh prepare.sh
      - uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Customize these paths based on your setup
          source: "site/"  # Replace with your directory
          branch: gh-pages                 # Replace with your Pages branch
      - name: FINAL 
        run: echo "https://torrezmn.github.io/"
